require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/tweets", type: :request do
  let(:account) { Account.create! email:"j@example.com", handle: "juggy" }
  # This should return the minimal set of attributes required to create a valid
  # Tweet. As you add validations to Tweet, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { message: "da tweet", account_id: account.id } }

  let(:invalid_attributes) { { message: "" } }

  describe "GET /index" do
    it "renders a successful response" do
      Tweet.create! valid_attributes
      get account_tweets_url(account), as: :json
      expect(response).to be_successful

      json = JSON.parse(response.body)
      expect(json.size).to eq(1)
      expect(json.first.dig("message")).to eq("da tweet")
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      tweet = Tweet.create! valid_attributes
      get account_tweet_url(account, tweet), as: :json
      expect(response).to be_successful

      json = JSON.parse(response.body)
      expect(json.dig("message")).to eq("da tweet")
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Tweet" do
        expect {
          post account_tweets_url(account),
               params: { tweet: valid_attributes }, as: :json
        }.to change(Tweet, :count).by(1)
      end

      it "renders a JSON response with the new tweet" do
        post account_tweets_url(account),
             params: { tweet: valid_attributes }, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Tweet" do
        expect {
          post account_tweets_url(account),
               params: { tweet: invalid_attributes }, as: :json
        }.to change(Tweet, :count).by(0)
      end

      it "renders a JSON response with errors for the new tweet" do
        post account_tweets_url(account),
             params: { tweet: invalid_attributes }, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end
end
